config/routes.rb
Rails.application.routes.draw do
  root 'machine_learning#index'

  resources :analogies, :only => [:index, :create] do
    post :guess, :on => :collection
    post :benchmark, :on => :collection
  end

  resources :image_searcher, :only => [:index] do
    get :search, :on => :collection
    post :benchmark, :on => :collection
  end

  resources :embeddings_based_search, :only => [:index] do
    get :search, :on => :collection
    post :benchmark, :on => :collection
  end

  resources :cca_search, :only => [:index] do

    get :search, :on => :collection
    get :search_description, :on => :collection
    post :benchmark, :on => :collection
  end

end

app/controllers/analogies_controller.rb
class AnalogiesController < ApplicationController

  def index

  end

  def create
    MachineLearning::Analogies.instance.analyze_matrix(params['glove-file'])
    # MachineLearning::ImageSearcher.instance.clear_and_pre_train!
    MachineLearning::ImageSearchBase.instance.pre_train!
    flash[:success] = 'Matrix loaded'
  end

  def guess
    @answer = MachineLearning::Analogies.instance.guess(params[:v1].strip, params[:v2].strip, params[:question].strip, params[:analogy_method])
  end

  def benchmark
    MachineLearning::Analogies.instance.benchmark(params[:analogy_method])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from MachineLearning::NoDatasetError do
    respond_to do |format|
      format.js { render 'machine_learning/no_dataset_error' }
    end
  end

end

app/controllers/cca_search_controller.rb
class CcaSearchController < ApplicationController

  before_action :validate_dataset, :only => [:benchmark, :search]

  def index

  end

  def search
    query = params[:q]
    k = params[:k].to_i if params[:k].present?

    @ranked_docs = MachineLearning::CcaSearch.instance.search(query, k)
  end

  def search_description
    @query = params[:q]
    k = params[:k].to_i if params[:k].present?

    @ranked_desc = MachineLearning::CcaSearch.instance.search_desc_img(@query, k)
  end

  def benchmark

    k = params[:k].to_i if params[:k].present?
    if params.keys.include?('image_search_method')
      @ranked_docs = MachineLearning::CcaSearch.instance.benchmark(k)
    else
      @ranked_docs = MachineLearning::CcaSearch.instance.reversed_benchmark(k)
    end
  end

  def validate_dataset
    raise MachineLearning::NoDatasetError if params[:image_search_method] != 'unigram' && MachineLearning::Analogies.instance.matrix.blank?
  end

end

app/controllers/embeddings_based_search_controller.rb
class EmbeddingsBasedSearchController < ApplicationController

  before_action :validate_dataset, :only => [:benchmark, :search]

  def index

  end

  def search
    query = params[:q]
    @ranked_docs = MachineLearning::EmbeddingsBasedSearch.instance.search(query)
  end

  def benchmark
    @ranked_docs = MachineLearning::EmbeddingsBasedSearch.instance.benchmark
  end

  def validate_dataset
    raise MachineLearning::NoDatasetError if params[:image_search_method] != 'unigram' && MachineLearning::Analogies.instance.matrix.blank?
  end

end

app/controllers/image_searcher_controller.rb
class ImageSearcherController < ApplicationController

  before_action :validate_dataset, :only => [:benchmark, :search]

  def index

  end

  def search
    query = params[:q]
    method = params[:image_search_method]
    aggr_method = params[:aggregation_method].to_sym
    MachineLearning::Description.mixed_lambda = params[:mixed_lambda].to_f
    MachineLearning::ImageSearcher.instance.pre_train!
    @ranked_docs = MachineLearning::ImageSearcher.instance.search(query, method, aggr_method)
  end

  def benchmark
    method = params[:image_search_method]
    just_test = params[:just_test] == '1'
    aggr_method = params[:aggregation_method].to_sym
    MachineLearning::Description.mixed_lambda = params[:mixed_lambda].to_f

    @ranked_docs = MachineLearning::ImageSearcher.instance.benchmark(method, aggr_method, just_test)
  end

  def validate_dataset
    raise MachineLearning::NoDatasetError if params[:image_search_method] != 'unigram' && MachineLearning::Analogies.instance.matrix.blank?
  end

end

app/controllers/machine_learning_controller.rb
class MachineLearningController < ApplicationController

  def index

  end
end

app/helpers/analogies_helper.rb
module AnalogiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_searcher_helper.rb
module ImageSearcherHelper
end

app/views/analogies/index.haml
%h1
  Analogies
%h2
  Import training dataset
  %i#dataset-uploaded-state.glyphicon.glyphicon-remove{style: "color: red; font-size: 18pt;"}
=form_tag analogies_path, multipart: true, :remote => true do

  .col-lg-6.col-sm-6.col-12
    .input-group
      %span.input-group-btn
        %span.btn.btn-primary.btn-file
          Browse&hellip;
          =file_field_tag 'glove-file', multiple: true
      %input.form-control{type: 'text', readonly: true}

  =submit_tag 'Analyze', class: 'btn btn-success'
#experiments.col-lg-12{hidden: true}
  .row
    %h2
      Your experiments
  .row
    %h3
      Choose analogy method
  =form_tag guess_analogies_path, :remote => true do
    .row
      =radio_button_tag :analogy_method, 'addition', true
      =label_tag :analogy_method_addition, 'Addition'
      =radio_button_tag :analogy_method, 'direction', false
      =label_tag :analogy_method_direction, 'Direction'
      =radio_button_tag :analogy_method, 'multiplication', false
      =label_tag :analogy_method_multiplication, 'Multiplication'
    .row
      %h3
        Ask something
    .row
      =text_field_tag :v1, '', class: 'col-sm-2'
      .col-sm-1='is to'
      =text_field_tag :v2, '', class: 'col-sm-2'
      .col-sm-1='like'
      =text_field_tag :question, '', class: 'col-sm-2'
      .col-sm-1='is to'
      =submit_tag 'Ask', class: 'btn btn-default col-sm-1'
      =label_tag :answer, 'Here will be result', class: 'col-sm-8', id: 'answer'
  .row
    %h3
      Run benchmark
    =button_to 'Addition', benchmark_analogies_path, class: "btn btn-default col-sm-3", remote: true, params: {:analogy_method => 'addition'}
    =button_to 'Direction', benchmark_analogies_path, class: "btn btn-default col-sm-3", remote: true, params: {:analogy_method => 'direction'}
    =button_to 'Multiplication', benchmark_analogies_path, class: "btn btn-default col-sm-3", remote: true, params: {:analogy_method => 'multiplication'}

app/views/cca_search/_search_results.haml
=image_tag("/datasets/Flicker8k_Dataset/#{document[0]}")

app/views/cca_search/_search_results_descriptions.haml
="#{description.description}"
%br

app/views/cca_search/index.haml
.container
  .row
    .col-md-6
      %h2
        Instructions
      %p
        Please put Flicker8k_Dataset pictures in public/datasets/Flicker8k_Dataset folder
        %br
        For using analogies upload glove vector file first:
        %i#dataset-uploaded-state.glyphicon.glyphicon-remove{style: "color: red; font-size: 18pt;"}
      =form_tag analogies_path, multipart: true, :remote => true do

        .col-lg-10.col-sm-6.col-12
          .input-group
            %span.input-group-btn
              %span.btn.btn-primary.btn-file
                Browse&hellip;
                =file_field_tag 'glove-file', multiple: true
            %input.form-control{type: 'text', readonly: true}

        =submit_tag 'Analyze', class: 'btn btn-success'

      =form_tag search_cca_search_index_path, :remote => true, method: :get do
        %h2
          Search picture
        .row
          .col-md-3
            .input-group
              =text_field_tag :k, '', class:'form-control input-lg', placeholder: 'K'
              %span.input-group-addon='%'
          #search-input.col-md-9
            .input-group
              =text_field_tag :q, '', class:'form-control input-lg'
              %span.input-group-btn
                =button_tag class:'btn btn-info btn-lg', type: :submit do
                  %i.glyphicon.glyphicon-search
      =form_tag search_description_cca_search_index_path, :remote => true, method: :get do
        %h2
          Search description
        .row
          .col-md-3
            .input-group
              =text_field_tag :k, '', class:'form-control input-lg', placeholder: 'K'
              %span.input-group-addon='%'
          #search-input.col-md-9
            .input-group
              =text_field_tag :q, '', class:'form-control input-lg'
              %span.input-group-btn
                =button_tag class:'btn btn-info btn-lg', type: :submit do
                  %i.glyphicon.glyphicon-search
      .row
        %h3
          Run benchmark
        =form_tag benchmark_cca_search_index_path, remote: true do
          .col-sm-3
            .input-group
              =text_field_tag :k, '', class: 'form-control', placeholder: 'K'
              %span.input-group-addon='%'
          %span.input-group-btn.col-sm-2
            =submit_tag 'Benchmark', name: :image_search_method, class: "btn btn-default "
            =submit_tag 'Benchmark_reversed', name: :image_search_reversed_method, class: "btn btn-default "


  .row
    %h2
      Search results
    #search-results
    #search-descriptions

app/views/embeddings_based_search/_search_results.haml
=image_tag("/datasets/Flicker8k_Dataset/#{document[0]}")

app/views/embeddings_based_search/index.haml
.container
  .row
    .col-md-6
      %h2
        Instructions
      %p
        Please put Flicker8k_Dataset pictures in public/datasets/Flicker8k_Dataset folder
        %br
        For using analogies upload glove vector file first:
        %i#dataset-uploaded-state.glyphicon.glyphicon-remove{style: "color: red; font-size: 18pt;"}
      =form_tag analogies_path, multipart: true, :remote => true do

        .col-lg-10.col-sm-6.col-12
          .input-group
            %span.input-group-btn
              %span.btn.btn-primary.btn-file
                Browse&hellip;
                =file_field_tag 'glove-file', multiple: true
            %input.form-control{type: 'text', readonly: true}

        =submit_tag 'Analyze', class: 'btn btn-success'

      =form_tag search_embeddings_based_search_index_path, :remote => true, method: :get do
        %h2
          Search picture
        .row
          #search-input
            .input-group.col-md-12
              =text_field_tag :q, '', class:'form-control input-lg'
              %span.input-group-btn
                =button_tag class:'btn btn-info btn-lg', type: :submit do
                  %i.glyphicon.glyphicon-search
      .row
        %h3
          Run benchmark
        =form_tag benchmark_embeddings_based_search_index_path, remote: true do
          =submit_tag 'Benchmark', name: :image_search_method, class: "btn btn-default col-sm-2"

  .row
    %h2
      Search results
    #search-results

app/views/image_searcher/_search_results.haml
=image_tag("/datasets/Flicker8k_Dataset/#{document[0]}")

app/views/image_searcher/index.haml
.container
  .row
    .col-md-6
      %h2
        Instructions
      %p
        Please put Flicker8k_Dataset pictures in public/datasets/Flicker8k_Dataset folder
        %br
        For using analogies upload glove vector file first:
        %i#dataset-uploaded-state.glyphicon.glyphicon-remove{style: "color: red; font-size: 18pt;"}
      =form_tag analogies_path, multipart: true, :remote => true do

        .col-lg-10.col-sm-6.col-12
          .input-group
            %span.input-group-btn
              %span.btn.btn-primary.btn-file
                Browse&hellip;
                =file_field_tag 'glove-file', multiple: true
            %input.form-control{type: 'text', readonly: true}

        =submit_tag 'Analyze', class: 'btn btn-success'

      =form_tag search_image_searcher_index_path, :remote => true, method: :get do
        %h2
          Search picture
        .row
          .col-sm-3
            %span.input-group-addon
              =radio_button_tag :image_search_method, 'unigram', true
              =label_tag :image_search_method_unigram, 'Unigram'
          .col-sm-3
            %span.input-group-addon
              =radio_button_tag :image_search_method, 'vectors', false
              =label_tag :image_search_method_vectors, 'Vectors'
          .col-sm-4
            .input-group
              =text_field_tag :mixed_lambda, '', class: 'form-control', placeholder: 'Lambda'
              %span.input-group-addon
                =radio_button_tag :image_search_method, 'mixed', false
                =label_tag :image_search_method_mixed, 'Mixed'

        .row
          ='Choose aggregation method:'
          =radio_button_tag :aggregation_method, 'aggregate_ranking_avg', true
          =label_tag :aggregation_method_average, 'Average'
          =radio_button_tag :aggregation_method, 'aggregate_ranking_best'
          =label_tag :aggregation_method_best, 'Best'

        .row
          #search-input
            .input-group.col-md-12
              =text_field_tag :q, '', class:'form-control input-lg'
              %span.input-group-btn
                =button_tag class:'btn btn-info btn-lg', type: :submit do
                  %i.glyphicon.glyphicon-search
      .row
        %h3
          Run benchmark
        =form_tag benchmark_image_searcher_index_path, remote: true do
          .row
            =check_box_tag :just_test, '1', true
            =label_tag :just_test, 'Just test data'
          .row
            ='Choose aggregation method:'
            =radio_button_tag :aggregation_method, 'aggregate_ranking_avg', true
            =label_tag :aggregation_method_average, 'Average'
            =radio_button_tag :aggregation_method, 'aggregate_ranking_best'
            =label_tag :aggregation_method_best, 'Best'
          =submit_tag 'Unigram', name: :image_search_method, value: 'unigram',  class: "btn btn-default col-sm-2"
          =submit_tag 'Vectors', name: :image_search_method, value: 'vectors', class: "btn btn-default col-sm-2"
          .col-sm-4
            .input-group
              =text_field_tag :mixed_lambda, '', class: 'form-control', placeholder: 'Lambda'
              %span.input-group-btn
                =submit_tag 'Mixed', name: :image_search_method, value: 'mixed', class: "btn btn-default"

  .row
    %h2
      Search results
    #search-results

app/views/layouts/_header.haml
.row.row-header
  .col-md-2
  %nav.col-md-8.center
    .btn-group
      =link_to 'Analogies', analogies_path, :class => 'btn-menu'
      =link_to 'Image Search', image_searcher_index_path, :class => 'btn-menu'
      =link_to 'Embeddings-Based NN Search', embeddings_based_search_index_path, :class => 'btn-menu'
      =link_to 'Multi-Modal Search', cca_search_index_path, :class => 'btn-menu'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Semantic Embeddings in Informatial Retrieval</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="header-container container-fluid">
  <%= render 'layouts/header' %>
</header>

<div class="body-container container-fluid">

  <div class="row row-core">
    <div class="left-section col-md-offset-1 col-md-2">
      <%= yield :left_panel %>
    </div>

    <div class="center-section col-md-6">
      <div class="unobtrusive-flash-container"></div>
      <%= yield %>
    </div>

    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>